import { generatorHandler, GeneratorOptions } from "@prisma/generator-helper";
import { writeFile } from "fs/promises";
import path from "path";

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "generated-output",
      prettyName: "Custom Generator",
    };
  },
  async onGenerate(options: GeneratorOptions) {
    const outputDir = options.generator.output?.value || "./generated-output";

    console.log("Custom Generator is running...");
    console.log("Schema path:", options.schemaPath);
    console.log("Output directory:", outputDir);

    // Example: Generate a simple file based on the Prisma schema
    const content = `// Generated by Custom Generator
const models = ${JSON.stringify(
      options.dmmf.datamodel.models.map((model) => model.name),
      null,
      2
    )};
console.log(models);
`;

    // Write the generated file
    await writeFile(path.join(outputDir, "generated.js"), content, "utf8");
    console.log("File generated successfully!");
  },
});
